
services:
  - docker

jobs:
  build:
    docker:
      - image: karthequian/gruyere:latest
      - image: gauntlt/gauntlt 

    steps:
      - run: |
           docker run --rm -d -p 8008:8008 karthequian/gruyere:latest
           docker ps -e
