version: 1

services:
  - docker

jobs:
  build:
    docker:
      - image: karthequian/gruyere:latest
      - image: gauntlt/gauntlt 

    steps:
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
           docker run --rm -d -p 8008:8008 karthequian/gruyere:latest
           docker ps
           ./scripts/circle-config.sh
           cat ./config/cucumber.yml
           docker run -t --rm -v $(pwd):/working -w /working gauntlt/gauntlt ./attacks/hello_world/hello-world.attack
           docker run -t --rm -v $(pwd):/working -w /working gauntlt/gauntlt ./attacks/env-vars/port-env-vars.attack
           docker run -t --rm -v $(pwd):/working -w /working gauntlt/gauntlt ./attacks/ci/xss.attack

